# Generated by Django 5.2 on 2025-04-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
